### ISSUE TITLE
Any links seems to be start redirected to this repo instead actual tweet

### ISSUE THREAD

**Issue by slord399** [FixTweet/FixTweet#480]
Any links seems to be start redirected to this repo instead actual tweet.
Wrong thambnail and redirect as it seems.
![image](https://github.com/FixTweet/FixTweet/assets/50810875/218331ef-a5d4-4509-b8a1-54a58f8a322a)

**Comment by SudosFTW** [comment]
Can confirm. Just started happening a bit ago.

**Comment by dangeredwolf** [comment]
Oops, I didn't notice the issue you opened up until now, but yes I pushed a broken change and it was up for a few minutes before I reverted it. The tweet in question appears to load again. I pushed a major change to how HTTP routing is handled (moving from itty-router to hono) and I broke something about it. If you find any other problematic URLs please let me know! If the issue is resolved then we can close this.
![image](https://github.com/FixTweet/FixTweet/assets/2636265/d1239e8b-5788-46fc-be59-e34b16f2b0ec)

**Comment by slord399** [comment]
Alright, I tried few new links and it still the same.

https://fxtwitter.com/i/status/1723124989011124275/
https://fxtwitter.com/i/status/1723125398815522940/
https://fxtwitter.com/i/status/1723125576800895155/
https://fxtwitter.com/i/status/1723125886843785552/

**Comment by dangeredwolf** [comment]
Ah, I see, the issue is the trailing slash. I have now deployed a fix that actually should work!
![image](https://github.com/FixTweet/FixTweet/assets/2636265/c1a3f581-3a09-4af0-af91-f8ed81ec97cb)

**Comment by slord399** [comment]
Alright, I can confirm it works for new link used but not existing.
Looks like some cached one be showing same.
![image](https://github.com/FixTweet/FixTweet/assets/50810875/918af065-f1ef-465f-aa7a-56eb965a46e8)

**Comment by dangeredwolf** [comment]
Yeah, unfortunately Discord's cached links will not clear. If you clear the trailing slash (or add a query string, etc) you will be able to reset an individual embeds to a working state.

**Comment by slord399** [comment]
Yeah, I believe so.
Alright, issue itself be clear so let me close ticket now.
